<a href="https://colab.research.google.com/github/OShev-11/Movie-Rating/blob/main/MovieRating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving ratings.csv to ratings.csv

In [3]:
import pandas as pd

In [4]:
rating = pd.read_csv('ratings.csv')
rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
rating.sort_values(by=['rating', 'timestamp'], ascending=[False, False]).head(5)

       userId  movieId  rating   timestamp
30174     210   177765     5.0  1537632257
46600     305   148671     5.0  1537354985
51318     331    57669     5.0  1537235356
51314     331    55820     5.0  1537235354
51202     331      608     5.0  1537235353